# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
pool:
  vmImage: 'Ubuntu 16.04'

trigger:
- master

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- script: npm run ci
  displayName: 'npm install'

- script: npm run test
  displayName: 'npm test'

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: ./test-results.xml

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'

- script: npm run lint
  displayName: 'npm test'