# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

trigger:
  - master

pr: none

stages:
  - stage: Build_Project
    jobs:
      - job: Build_Project
        pool:
          vmImage: "Ubuntu-16.04"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "10.x"

          - script: npm ci
            displayName: "Install Dependencies"

          - script: npm run build
            displayName: "Build Project"
  - stage: Build_Docker
    dependsOn: Build_Project
    jobs:
      - job: Build_Docker
        pool:
          vmImage: "Ubuntu-16.04"
        steps:
          - task: Docker@2
            displayName: "Build azuredevx/git-rest-api"
            inputs:
              containerRegistry: "git-rest-api docker"
              repository: "azuredevx/git-rest-api"
  - stage: Publish_Docker
    dependsOn: Build_Docker
    jobs:
      - job: Publish_Docker
        pool:
          vmImage: "Ubuntu-16.04"
        steps:
          - task: Docker@2
            displayName: "Push azuredevx/git-rest-api"
            inputs:
              containerRegistry: "git-rest-api docker"
              repository: "azuredevx/git-rest-api"
