trigger:
  - master

pr: none

stages:
  - stage: Build_Docker
    jobs:
      - job: Build_Docker
        displayName: Build and publish to dockerhub.io
        pool:
          vmImage: "Ubuntu-16.04"
        steps:
          - script: |
              version=$(npm run -s get-version)
              echo "##vso[task.setvariable variable=NpmVersion;]$version"

          - script: echo 'Version is $(version) or $version'
          # - task: Docker@2
          #   displayName: "Build azuredevx/git-rest-api"
          #   inputs:
          #     containerRegistry: "git-rest-api docker"
          #     repository: "azuredevx/git-rest-api"
          #     tags: |
          #       $().$(Build.BuildNumber)
          #       latest

  - stage: build_sdks
    displayName: Build SDKs
    dependsOn: []
    jobs:
      - job: build
        pool:
          vmImage: "Ubuntu-16.04"
        steps:
          - script: npm -s ci
            displayName: Install
          - script: npm -s run sdk:gen
            displayName: Generate SDKs
          - script: npm -s pack
            workingDirectory: sdk/out/typescript
            displayName: Pack
          - task: CopyFiles@2
            displayName: 'Copy Files to: drop'
            inputs:
              sourceFolder: ./sdk/out/typescript
              contents: '*.tgz'
              targetFolder: $(Build.ArtifactStagingDirectory)/drop
          - task: PublishPipelineArtifact@0
            inputs:
              artifactName: "drop"
              targetPath: $(Build.ArtifactStagingDirectory)/drop